# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/apps/web'
    schedule:
      interval: 'daily'
    target-branch: 'beta'

  # Add Python package ecosystem for audiotkit
  - package-ecosystem: 'pip'
    directory: '/packages/audiotkit'
    schedule:
      interval: 'daily'
    target-branch: 'beta'

  # Add Python package ecosystem for audiotkit_ai
  - package-ecosystem: 'pip'
    directory: '/packages/audiotkit_ai'
    schedule:
      interval: 'daily'
    target-branch: 'beta'
