replicaCount: 2

image:
  repository: your-dockerhub-username/audiokit-ai
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false

resources: {}
nodeSelector: {}
tolerations: []
affinity: {} 