apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiokit-ai
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: audiokit-ai
  template:
    metadata:
      labels:
        app: audiokit-ai
    spec:
      containers:
        - name: audiokit-ai
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres/audiokit_ai_db" 